#+TITLE:Ada/SPARK support for Emacs org-babel


** Introduction
=ob-ada-spark.el= file provides support for Ada/SPARK languages in the context
of Emacs' =org-babel=, part of =org-mode=, to evaluate block codes written in
different programming languages.

Ada/SPARK supports compiling and running Ada and SPARK code (=gantmake=), as
well as proving SPARK programs using formal verification tools provided in SPARK
(=gnatprove=).

This is a very preliminary version.

** Installation
Ada/SPARK support is still not part of Emacs. As long as it cannot be found as
part of some Emacs distribution, you have to download and load it from this
repository. For now, just load it in Emacs, open an =org= file and enjoy.
Additional and detailed information will be provided soon.

CAVEAT: To have font highlight (keywords, variables) in Ada/SPARK code blocks in
=org-babel= , it is necessary to have =ada-mode= installed and open and Ada file
in Emacs before the =org= file.

** Examples
Please see some screenshots in the [[file:./images/README.org][images directory]].
